export interface Listcheck{
userNameVehiculo:string;
userNameConductor:string;
kmActual:number;
cambioAceite:number;
llantas:string;
neumaticos:string;
cinturonesDeSeguridad:string;
puertas:string;
asientos:string;
espejosRetrovisores:string;
kitDeCarreteras:string;
sistemaDeLuces:string;
primerosAuxilios:string;
llantasDeRepuesto:string;
parabrisas:string;
vidrios:string;
limpiaparabrisas:string;
refrigeranteoAgua:string;
aceiteDelMotor:string;
aceiteHidraulico:string;
liquidoDeFrenos:string;
bateria:string;
fecha:string;
observaciones:string;
}